
PHASER_ROW_NUM = '__phaser_row_num__'

ON_ERROR_WARN = "ON_ERROR_WARN"
ON_ERROR_COLLECT = "ON_ERROR_COLLECT"
ON_ERROR_DROP_ROW = "ON_ERROR_DROP_ROW"
ON_ERROR_STOP_NOW = "ON_ERROR_STOP_NOW"

CSV_FORMAT = "CSV"
JSON_RECORD_FORMAT = "JSON_RECORD"
SUPPORTED_FORMATS = [CSV_FORMAT, JSON_RECORD_FORMAT]